CREATE TABLE [dbo].[CUSTOMER] (
    [CUST_CODE]       VARCHAR (6)     NOT NULL,
    [CUST_NAME]       VARCHAR (40)    NOT NULL,
    [CUST_CITY]       CHAR (35)       NULL,
    [WORKING_AREA]    VARCHAR (35)    NOT NULL,
    [CUST_COUNTRY]    VARCHAR (20)    NOT NULL,
    [GRADE]           DECIMAL (18)    NULL,
    [OPENING_AMT]     DECIMAL (12, 2) NOT NULL,
    [RECEIVE_AMT]     DECIMAL (12, 2) NOT NULL,
    [PAYMENT_AMT]     DECIMAL (12, 2) NOT NULL,
    [OUTSTANDING_AMT] DECIMAL (12, 2) NOT NULL,
    [PHONE_NO]        VARCHAR (17)    NOT NULL,
    [AGENT_CODE]      CHAR (6)        NOT NULL,
    PRIMARY KEY CLUSTERED ([CUST_CODE] ASC),
    FOREIGN KEY ([AGENT_CODE]) REFERENCES [dbo].[AGENTS] ([AGENT_CODE])
);

